### ISSUE TITLE
Element value must be a constant expression

### ISSUE THREAD

**Issue by Christophe668** [andretietz/retroauth#13]
Hi,

In my project the line 
```
@Authentication(accountType = R.string.auth_account_type, tokenType = R.string.auth_token_type)
```
does not want to compile, I get this error :
Error:(6, 39) error: element value must be a constant expression

The R.string does not seems to be seen as a constant.

Thanks !

**Comment by Christophe668** [comment]
This seems to be related to the fact that I'm inside a module, I'll investigate but it this is not directly related to your library so I'm closing this issue.

**Comment by Unic8** [comment]
Please post a solution, if you found one. to avoid repostings of this issue. Thank you for reporting anyway.

**Comment by Christophe668** [comment]
Hi Unic8, 

I found this article, maybe this will interest you. Do you think there could be a solution to this? 
https://github.com/excilys/androidannotations/wiki/Library-projects

Thank you !

**Comment by Unic8** [comment]
So you want to write a library ontop of retroauth? I don't recommend this, since may be, the one who's using your library doesn't want to have retroauth as a dependency.

**Comment by Unic8** [comment]
But I agree, this would be nice to support. I'll add a feature-request. But I can't promise anything in the close future.

**Comment by Christophe668** [comment]
Hi, no no I'm not trying to write on top of it. The thing is, I use separate modules for my project and my server is inside another module than my app module.

Thanks !

**Comment by andretietz** [comment]
Please use Version 2, there you have to use constant strings.
