### ISSUE TITLE
this activity cannot be started without the accountype extra in the intent

### ISSUE THREAD

**Issue by dieter115** [andretietz/retroauth#14]
hi Unic8

i'm using your library but i can't start my  activity that extends your authenticationactivity because of this error :      Caused by: java.lang.RuntimeException: This Activity cannot be started without the "accountType" extra in the intent!.

I hope you now the reason

**Comment by Unic8** [comment]
Yes, I do know the reason. I did this with intention to avoid someone is calling your LoginActivity without an account type.

One of the good things of the retroauth library is, that you actually don't need to call you LoginActivity manually. If a request requires it, it'll open by itself.

If (for some reason) you still want to do this manually
Either : 
 * use AuthAccountManager#addAccount(Activity activity, String accountType, String tokenType)
or
 * add the Extra parameter to your Intent, which you use to create the activity

like:
    
    intent.putExtra(AccountManager.KEY_ACCOUNT_TYPE, getString(R.string.your_account_type))


Tell me if that was working, so I can close this issue!
