### ISSUE TITLE
retroauth 2.0 New features

### ISSUE THREAD

**Issue by xiaolongyuan** [andretietz/retroauth#18]
Version 2.0 will automatically manage and use the refresh_token the refresh access_token?

**Comment by andretietz** [comment]
Not directly. Take a look to the documentation of [retroauth-android step4](https://github.com/andretietz/retroauth/tree/feature/rebuild/retroauth-android). There's a dummy implementation. In the demoandroid, there's actually a working implementation using google tokens (including refresh)
