### ISSUE TITLE
Setting action, account and token resources when using Retroauth in a library project

### ISSUE THREAD

**Issue by leovanhaaren** [andretietz/retroauth#23]
I'm using Retroauth in a library (core) project. The trouble im getting is that I cannot define the string.xml resources because a library project's strings are not final/constants. Is there any way of getting around this? (or modifying the project a bit)

**Comment by andretietz** [comment]
yes. You can additionally "predefine" strings you have to implement in the app using this library using the same approach, the library itself is using.
```xml
    <resources>
        <item name="com.andretietz.retroauth.authentication.ACTION" type="string" />
    </resources>
```

**Comment by andretietz** [comment]
I just tried this out! You're right, this is if course an issue.

**Comment by leovanhaaren** [comment]
When using the 2.0 version (before the switch from string to int) all works fine. Seems like Butterknife had the same problem before, but they never fixed it. (Library project resources are not defined as final static because of speed advantages)

https://github.com/JakeWharton/butterknife/issues/45

**Comment by andretietz** [comment]
This is because of the "reindexing" of the resource ids on newer android build systems. On the build time of the library, the build system does not set the values to "constant" so, that on build time of the app, this value can be overridden.

**Comment by andretietz** [comment]
Milestone for the non-final AndroidTokenStorage

**Comment by leovanhaaren** [comment]
Thanks! This will do for now 👍 

I'll keep a close eye watching the 2.1.1 version.

**Comment by andretietz** [comment]
I did't like the solution with making it non final. I found a nicer one. Since the TokenType creation shouldn't be part of the TokenStorage, I will create a TokenTypeFactory, which you then can easily override, when creating the AndroidAuthenticationHandler.

**Comment by andretietz** [comment]
It's done! New release version is 2.1.1

Use:

    AndroidAuthenticationHandler.create(new MyProvider(), new MyTokenTypeFactory())
