### ISSUE TITLE
make finalizeAuthentication not finalize

### ISSUE THREAD

**Issue by leovanhaaren** [andretietz/retroauth#33]
Just a thought, why is this method finishing the activity? Maybe you can break it up, because for my case after login the user might need to follow a onboarding process, so finishing the activity makes no sense yet.

For now i've just created my own variant of the AuthenticationActivity, but it might be easier for others if finishing the activity is optional :)

**Comment by andretietz** [comment]
@leovanhaaren 2.1.2 released, which contains the option, to avoid finishing the Activity:

https://github.com/andretietz/retroauth/blob/master/retroauth-android/src/main/java/com/andretietz/retroauth/AuthenticationActivity.java#L147
