### ISSUE TITLE
Custom TokenTypeFactory<String> fails in 2.1.3

### ISSUE THREAD

**Issue by leovanhaaren** [andretietz/retroauth#41]
AndroidAuthenticationHandler.create(provider, new CustomTokenTypeFactory());

Wrong 2nd argument type. Found: 'com.imin.core.auth.CustomTokenTypeFactory', required: 'com.andretietz.retroauth.TokenTypeFactory<com.andretietz.retroauth.AndroidTokenType>'

Not sure why this fails, because the tests do work

**Comment by andretietz** [comment]
Did you try to clean the project?

**Comment by andretietz** [comment]
This seems to be a problem with the snapshot version only. I'll create a release for you ;)

**Comment by andretietz** [comment]
2.1.3 done. I figured out this is a bug in my jfrog snapshot deploy script. I'll work on it.

**Comment by leovanhaaren** [comment]
Thanks for creating the release, still getting the error mentioned above which is weird. Somehow it's not recognising the TokenTypeFactory<TOKEN_TYPE> interface. Maybe this is a android studio bug, will check further. :)
