### ISSUE TITLE
ANDROID OperationCanceledException on authenticated call

### ISSUE THREAD

**Issue by pstkweb** [andretietz/retroauth#46]
I'm trying to use your utility with my own OAuth server and API. 

I had followed your tutorial but when I try to call asynchronously an authenticated method it throws an `AuthenticationCanceledException` which contains an `OperationCanceledException` triggered by `android.accounts.AccountManager$AmsTask.internalGetResult(AccountManager.java:1503)` in `com.andretietz.retroauth.AndroidTokenStorage.getToken(AndroidTokenStorage.java:87)`.

My service is defined as : 

``` java
@Authenticated({R.string.authentication_ACCOUNT, R.string.authentication_TOKEN})
@GET("me")
Call<CurrentPerson> getMe();
```

And it is called in an activity `onCreate` : 

``` java
// SnPAPIHandler::getApiService() returns the service defined above
Call<CurrentPerson> call = SnpAPIHandler.getInstance().getApiService().getMe();
call.enqueue(new Callback<CurrentPerson>() {
    @Override
    public void onResponse(Call<CurrentPerson> call, Response<CurrentPerson> response) {
        if (response.isSuccessful()) {
            // Populate activity view
        } else {
            // Display an error message
        }
    }

    @Override
    public void onFailure(Call<CurrentPerson> call, Throwable t) {
        // The exception is catched here!
        t.printStackTrace();
        Log.e("AUTH ERR", "Error", t);
        // Display an error message
    }
});
```

What am I missing?

**Comment by andretietz** [comment]
On which version are you running? make sure it's the latest (2.1.4)

Did you try this on another device? (just wanna make sure this isn't a device dependent thing)

May be debug into "AndroidTokenStorage.java:87" and see if activity is non null.

If all this is not helping please try to provide me something to reproduce this! In the easierst case this would be a test, in the worst a small project. I'll totally hunt this down! ;)

**Comment by andretietz** [comment]
Still having this problem?

**Comment by pstkweb** [comment]
Sorry I didn't had time to debug and test this, I'll try this week.

**Comment by pstkweb** [comment]
Here some news : 
- it's the latest version (2.1.4)
- I try with other virtual devices => same problem
- I don't master debugging but I added a breakpoint to the `getToken` method and it was never reached
- The login activity actually popup but when it goes back to the "authenticated" activity it throws the error. As I said the `Call` ran in the activity's `onCreate`

**Comment by andretietz** [comment]
Do you know how to reproduce this in code?

I really would like to hunt this one down, but in the example app I cannot reproduce it. Could you create a branch with a min example to reproduce this? It would be enough if you change the demo project and send a PR (don't worry about may failing tests for this).

**Comment by andretietz** [comment]
Is this still an issue?

**Comment by andretietz** [comment]
Seems no issue anymore, since the author is not responding
