### ISSUE TITLE
Account chooser intent or getAccounts methods

### ISSUE THREAD

**Issue by iagocanalejas** [andretietz/retroauth#48]
Could be nice to have this method so developers can launch a chooseAccountIntent using your class.
Or maybe directly wrap the AccountManager.newChooseAccountIntent. Something like:

```java
   public Intent getAccountSelectorIntent(@NonNull String accountType) {
        ArrayList<Account> accounts = new ArrayList<> (Arrays.asList(mAccountManager.getAccountsByType(accountType)));
        Account account = getActiveAccount(accountType);
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
            return AccountManager.newChooseAccountIntent(account, accounts,
                    new String[]{getString(R.string.authentication_ACCOUNT)}, null, null,
                    null, null);
        } else if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.GINGERBREAD) {
            return AccountManager.newChooseAccountIntent(account, accounts,
                    new String[]{getString(R.string.authentication_ACCOUNT)}, false, null, null,
                    null, null);
        } else {
            return AccountPicker.newChooseAccountIntent(account, accounts,
                    new String[]{getString(R.string.authentication_ACCOUNT)}, false, null,
                    getString(R.string.authentication_TOKEN), null, null);
        }
    }
```

**Comment by andretietz** [comment]
Well, I just checked.

Easiest solution is to resetActiveAccount and fire an authenticated request.

You're right a method to switch accounts would be nice.

How does AuthAccountManager.switchAccount(tokentype) sounds to you?

Will be in the next version ;)

**Comment by iagocanalejas** [comment]
Nono, i mean use android AccountManager.newChooseAccountIntent directly from your AuthAccountManager class. This would be useful to avoid get a new AccountManager instance in case multiple accounts were logged. Still don't know if i am explaining. Just include the method i wrote above in your AuthAccountManager class will do the trick.

**Comment by iagocanalejas** [comment]
Yeah that sounds great thanks to take a look about it :) but why tokenType instead accountType?

**Comment by andretietz** [comment]
sorry my mistake, updated the comments.

Would that fulfill your needs?

**Comment by iagocanalejas** [comment]
For sure, thank you a lot for the work in this library. It's a great one.

**Comment by andretietz** [comment]
Ahh ok, now I get it. You want to use the Android AccountManager Intent method.

I'll take a closer look, may be I can replace this dialog then (even if I thought about this once before, but don't remember why I havn't done this)

**Comment by andretietz** [comment]
Check this out:
https://github.com/andretietz/retroauth/pull/50

I wrapped it up a bit changed a few things here and there, but this seems good. Do you agree on that?

**Comment by iagocanalejas** [comment]
Seems nice, this would for sure work for me

**Comment by andretietz** [comment]
It's in Version 2.1.6

https://github.com/andretietz/retroauth/blob/2.1.6/retroauth-android/src/main/java/com/andretietz/retroauth/AuthAccountManager.java#L264

**Comment by iagocanalejas** [comment]
Working perfect thank you
