### ISSUE TITLE
Enable Locking doesn't seem to be working

### ISSUE THREAD

**Issue by ChrisTitos** [andretietz/retroauth#54]
As you mentioned enableLocking in #43 , my understanding is that if I set this to true, I can fire multiple requests at (more or less) the same time, and they will wait for each other to authenticate.

So that's what I'm doing. I set it to true, on app startup I do several calls, and all calls use the same account type and token. However the login activity is opened for each call.

When I'm debugging I can see that there is a lock for each call in the `CredentialInterceptor.TOKENTYPE_LOCKERS` Hashmap. Is that supposed to be the case? All my calls are annotated exactly the same way:
`@Authenticated({R.string.account_type, R.string.authentication_token})`
(by the way, is there a way to set a default `@Authenticated` for all calls?)

Is this a bug or am I doing something wrong? Or am I misunderstanding enableLocking?

**Comment by andretietz** [comment]
Hey, sorry for the late response, I have been in in holidays.

1. It seems like a bug. I am currently researching a better way of locking for this case. So I won't fix this wrong behaviour, but will find a better way soon. 

2. Yes. There is a way of setting a default, which I'm using regulary, since most of the time you only have one token and account type. Implement your own TokenTypeFactory:

    MyTokenFactory implements TokenTypeFactory<AndroidTokenType>


and use it in your own implementation of the AuthenticationHandler (see: [AndroidAuthenticationHandler](https://github.com/andretietz/retroauth/blob/master/retroauth-android/src/main/java/com/andretietz/retroauth/AndroidAuthenticationHandler.java))


I hope this was helping

**Comment by ChrisTitos** [comment]
> Yes. There is a way of setting a default, which I'm using regulary, since most of the time you only have one token and account type. Implement your own TokenTypeFactory:

Thanks, that works :)

> It seems like a bug. I am currently researching a better way of locking for this case. So I won't fix this wrong behaviour, but will find a better way soon.

Great. For now I can make sure I do one call first, but the neater solution would be this locking functionality.

**Comment by andretietz** [comment]
Hey, I found the problem with the locking, which is pretty simple to fix. I'll try to release a patch for this asap. In the long term I will refactor this anyway.

**Comment by ChrisTitos** [comment]
Great. Looking forward to the patch

**Comment by andretietz** [comment]
In a couple of minutes there's a new snapshot version (2.2.2-SNAPSHOT) available. Please test if that fits your case now and let me know. After you told me if this was working I'll create the release

**Comment by ChrisTitos** [comment]
I can confirm it is fixed.

Though I am now running into another problem, which might be related to this. When I cancel the login (by clicking back), is that status stored somewhere or something? Because when I cancel, and restart the app, I simply get a AuthenticationCanceledException for the call, the LoginActivity is not called again until I do a different call.

**Comment by andretietz** [comment]
Mhh... No, the status is not stored. When 2 requests are fired and one of it is canceled, the otherone should be canceled too. after this it should restart automatically the whole checking flow.

**Comment by ChrisTitos** [comment]
I'm thinking it's on my side of things. You can ignore it for now and close this issue.

**Comment by andretietz** [comment]
I think this can happen if you're using one thread or a pool of threads, however less threads than requests. Try using foreach request another thread. Otherwise they cannot be blocked correctly. (on rx use Schedulers.newThread())
