### ISSUE TITLE
Authorize a whole service and anonymous methods support

### ISSUE THREAD

**Issue by juanpmarin** [andretietz/retroauth#55]
Hi, great library !

I think that would be useful if I could annotate a service as authorized and mark the unauthorized methods as anonymous, It would be possible ? 

Thanks

**Comment by andretietz** [comment]
I thought about this too, but decided against it.

What you can do to simplify your code is:

Implement your own TokenTypeFactory:

    MyTokenFactory implements TokenTypeFactory<AndroidTokenType>


and use it in your own implementation of the AuthenticationHandler (pretty simple to implement, see: [AndroidAuthenticationHandler](https://github.com/andretietz/retroauth/blob/master/retroauth-android/src/main/java/com/andretietz/retroauth/AndroidAuthenticationHandler.java))

This way you can tell your TokenTypeFactory what types to use and forget about them in the annotations.

so you can use them like this:

``` 
interface Foo {
    @Authenticated
    @GET(...)
    Call<Response> someCall();
}
```
