### ISSUE TITLE
Login activity opens only after second launch

### ISSUE THREAD

**Issue by alashow** [andretietz/retroauth#62]
Hi. Awesome library, just what I needed!

I started implementing it today, learning from demos because as of 3.0.0-beta1 some parts of docs are outdated.

I have this problem:

1. The app opens, retrofit immediately fails with an error `com.andretietz.retroauth.AuthenticationCanceledException`, retrying the request fails.
2. After putting the app in background then returning back, retrying opens login activity.
For example:
I press back button from main activity (i.e close the app), then open it, login activity opens.
I lock my phone then unlock and retry the request, login activity opens. 
I press home button to minimize the app, then return and retry the request, login activity opens. 

3. If I clear the app from recent apps (i.e kill the app/process), it starts from 1.

What might be the problem?
Thanks.

**Comment by andretietz** [comment]
Hey, this is why it's still a beta ;)

I just created a PR #63 which may help you

**Comment by alashow** [comment]
The only difference I could see is creating new service instead of using provided one (`RetroauthAuthenticationService`).
So I created one, but still same behavior.

**Comment by andretietz** [comment]
You have a link to some code?

**Comment by alashow** [comment]
I think I included all related files here: https://gist.github.com/alashow/e805c64b95eba1df1ed9c90c43f2743d

**Comment by andretietz** [comment]
Could you try to debug into the refresh method? Is that called right before the AuthenticationCanceledException? If so, I might have a clue

**Comment by alashow** [comment]
No, it's not hitting refreshMethod. Even when login activity opens.

**Comment by andretietz** [comment]
Try using the snapshot version:

3.0.0-beta2-SNAPSHOT. There is a change that might fix it. If not I have another idea, but I need a bit more details on how to reproduce this problem

**Comment by alashow** [comment]
Currently, there are no accounts.
`3.0.0-beta2-SNAPSHOT` fails to resolve.

**Comment by alashow** [comment]
Now it's resolved.

No luck, same behavior.

**Comment by alashow** [comment]
What details can I provide?

**Comment by andretietz** [comment]
Mh... best would be a modification of the demo project that reproduces the problem in a separate branch

**Comment by alashow** [comment]
I tried demo project: no, it works as intended.

**Comment by andretietz** [comment]
ok I tried to add a fix. This particular issue was in an earlier version already.
So ATM it is creating a new snapshot version. make sure that your [snapshotversion gets update correctly](https://stackoverflow.com/questions/18344356/how-do-i-manage-changing-snapshot-depencies-with-android-studio)

**Comment by alashow** [comment]
I think it's not fixed yet, as I tried the latest snapshot and facing the same behavior.

**Comment by andretietz** [comment]
did you make sure that the "old" snapshot was removed?

**Comment by alashow** [comment]
Yes, I removed files manually, added `changing = true` and run clean task.

**Comment by andretietz** [comment]
If this should not be fixed, I would like to see this implementation in detail. if you can give me temporary access to some bitbucket,github or similar, that would help a lot.

**Comment by andretietz** [comment]
Thanks to @alashow I found the problem. I'll find a solution for it.
