### ISSUE TITLE
Host on maven central

### ISSUE THREAD

**Issue by vanniktech** [andretietz/retroauth#65]
Can we also upload this library to maven central?

Bintray has been down in the past and it seems like it is down again today and mavenCentral() is much more reliable.

AFAIK bintray can sync to maven central - there's more information [here](https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html).

**Comment by vanniktech** [comment]
Yeah they're fixed now.

**Comment by andretietz** [comment]
Since this is no change on the code itself, I'll try doing this soon.

**Comment by andretietz** [comment]
https://issues.sonatype.org/browse/OSSRH-40481?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel

**Comment by andretietz** [comment]
https://search.maven.org/#search%7Cga%7C1%7Cretroauth
