### ISSUE TITLE
Can not understand these two lines,  necessary?

### ISSUE THREAD

**Issue by XinyueZ** [andretietz/retroauth#66]
https://github.com/andretietz/retroauth/blob/8b5c003e32acf19a85d1c28fc510c0a1a5d10eee/gradle/publish.gradle#L20

**Comment by andretietz** [comment]
They're not relevant for the library itself, it just helps me release them.
In the modules gradle.properties, they can be redefined, I am using this script for other libraries too.

With that, I can use the same script within multiple libraries.

**Comment by XinyueZ** [comment]
i.c
