### ISSUE TITLE
Best way to implement "Anonymous" access (OAauth client_credentials)

### ISSUE THREAD

**Issue by ChrisTitos** [andretietz/retroauth#67]
Hi,

Up to now my app has only used this library to login a user. However, I'm now adding a "sign up" functionality, and for this I need anonymous access to my API using the OAuth client_credentials grant. 

My guess is define a different token type. But it seems this library will always open a Login Activity? But I don't need an activity for this case (plus, the Login activity is already opened because the "sign up" button is in that activity).

Any suggestions?

**Comment by andretietz** [comment]
Did this help?

**Comment by ChrisTitos** [comment]
Maybe "userless" is a better term than anonymous. If the user is not logged in, the app itself still needs to make calls to the API, and for that it still needs to get an access token via OAuth (via the client credentials grant). 
For this no user interaction is required, so I don't want to open a Login screen (even if I immediately close it, you still get a flash).  Also, the primary use case here is a user sign-up, and in this case I am already in the LoginActivity (from there the user clicks on "create account" and goes to the sign-up flow), so you could get weird situations.

So yes, a token type seems to be one part of the solution, but if I could then do something like:

```
TokenType A (user, interaction required) -> open login screen
TokenType B (userless, no interaction required) -> directly call the login logic
```

**Comment by andretietz** [comment]
ok, then just don't user the authenticated annotation but a manually set, header.
