### ISSUE TITLE
Requests are stuck after logging out

### ISSUE THREAD

**Issue by alashow** [andretietz/retroauth#68]
Hey,

I'm not sure if it's related to retroauth or not, but I have this edge case issue:
- User opens the app (MainActivity)
- Network request is made with `@Authenticated`
- API returns an `auth error`, because the token is no more valid (or some other token related error)
- App catches the error and logs out the user: removes the active owner (`ownerManager.getActiveOwner()`, `ownerManager.removeOwner()`), opens LoginActivity with clear top
- When the app is trying to log out the user, if the user quickly clicks back or some other UI button that opens another screen or else: LoginActivity opens, but the user can click back button and open MainActivity which was supposed to be cleared from the stack (or other last clicked screen)
- At this point, App gets to MainActivity or other screens that shows the last error `auth error`. If the user clicks a retry button or refreshes via swipeRefresh: App retries the network request with `@Authenticated`. The expected behavior is to open `LoginActivity` or account chooser because last active owner was removed. But it somehow gets stuck, and App doesn't receive any errors and stays in the loading state. If the user invokes another UI element that makes another network request, the last request gets canceled (rxjava's `disposables.clear()`) and throws swallowed `android.accounts.OperationCanceledException`.

When I started writing this, I wasn't sure if it was retroauth's bug, but now as I know where it gets stuck, it seems like it's retroauth's bug :). I don't know if it can be replicated or not though.

Have you had this issue before?
I'm using version `3.0.0-beta6`

Thanks.

**Comment by andretietz** [comment]
I am already aware of this issue, since at our company we're using it in production (not the beta yet).

The only solution for this is canceling the request, as soon as a login is required. I just never had the time to fix this yet.

**Comment by andretietz** [comment]
This PR should fix the issue.

**Comment by andretietz** [comment]
please try the last snapshot version 3.0.0-beta6-SNAPSHOT

**Comment by alashow** [comment]
Which repo do I need to add for snapshots?

**Comment by alashow** [comment]
Yes, it throws `AuthenticationRequiredException` now.
Is that the intended behavior? I thought it will open login activity by itself

**Comment by andretietz** [comment]
Hey, yes, the `AuthenticationRequiredException` is intended. This is because I have to cancel the requested request, when opening up the LoginActivity.

The activity should open anyways. Please try that using the demo application.

**Comment by andretietz** [comment]
there's a beta release out now. 3.0.0-beta7 (in a few minutes)

**Comment by alashow** [comment]
The exception is alright - but it's not opening the login activity (I guess that's not good if it should always open). But I was able to detect it from my global retrofit error handler that can open login activity.

Anyways, after I added some flags to my login intent on log out, I can't reproduce the original error (had to remove flags to test this).

BTW. I think Bitrise builds are for your only (or your organization).

**Comment by andretietz** [comment]
Can you reproduce the opening-problem using the demo app?

**Comment by alashow** [comment]
I just cloned and run the demo app.
I can't reproduce on it because it doesn't have separate UI for authenticated users and doesn't open login activity on log out.

Anyways. Everything is okay right now:
1. It doesn't get stuck/locked like before.
2. Even it does, now I don't allow going back.
