### ISSUE TITLE
[FORMAT]Kotlin source files need format

### ISSUE THREAD

**Issue by XinyueZ** [andretietz/retroauth#69]
The source code has a strange format and incompatible with IDE. Each time when people want to add codes there're different tabs and spaces. Has the project used common Kotlin format which is provided in Android Studio ?

**Comment by andretietz** [comment]
https://github.com/andretietz/retroauth/pull/72/commits/dc057e7e279e46b1b3454c5ccfe7799fa1b641a8

**Comment by XinyueZ** [comment]
why not enable `ktlint` which can complete code format automatically and with standard format scheme ?

**Comment by andretietz** [comment]
good idea, I am on it

**Comment by alashow** [comment]
I recommend [`spotless`](https://github.com/diffplug/spotless) which can use ktlint and provides gradle task for formatting (it an use ktlint for kotlin).

**Comment by XinyueZ** [comment]
It's done
