### ISSUE TITLE
[BUG]RetroauthInitProvider.kt has unsafe null-point.

### ISSUE THREAD

**Issue by XinyueZ** [andretietz/retroauth#79]
https://github.com/andretietz/retroauth/blob/ea84cf9bf864b9edc290276e0869ae374ec8abfd/retroauth-android/src/main/java/com/andretietz/retroauth/RetroauthInitProvider.kt#L13
Kotlin-plugin reports:
> Unsafe use of a nullable receiver of type Context?

Kotlin-plugin: 1.2.61
AS Gradle: 3.3.0

**Comment by andretietz** [comment]
`context` is a kotlinified version of `getContext()` which is never null in the onCreate method
