### ISSUE TITLE
Version 3, backwards compatibility of existing (refresh) tokens/accounts?

### ISSUE THREAD

**Issue by ChrisTitos** [andretietz/retroauth#82]
Hi,

I'm looking in to migrating to version 3 of the library, and had some questions regarding backwards compatibility of accounts and tokens stored with version 2.

1) Does v3 work with owners/tokens stored with v2?
2) How is the refresh token stored now? V2 AndroidToken had a refresh token parameter that seems to be gone in V3. (the Javadoc of `AuthenticationActivity ` seems to be outdated)

**Comment by andretietz** [comment]
1: The v3 tokens should be compatible with v2 except the refresh tokens. Refresh-Tokens are stored different, as you mentioned already. 

Compare:
https://github.com/andretietz/retroauth/blob/2.3.2/retroauth-android/src/main/java/com/andretietz/retroauth/AndroidTokenStorage.java
vs.
https://github.com/andretietz/retroauth/blob/3.0.0-beta7/retroauth-android/src/main/java/com/andretietz/retroauth/AndroidTokenStorage.kt

2: The refresh token must be stored as user data within the `AndroidToken`. A good example would be the Facebook example in the demo app. In there, I am not storing a refresh token, but a token time limit. With that you can even refresh the token without hitting a 401. 
If you want to store a refresh token, just use the same approach as with the validity in the example.

Make sure you're adding this value to the token type, as it is here:
https://github.com/andretietz/retroauth/blob/master/demoandroid/src/main/java/com/andretietz/retroauth/demo/FacebookAuthenticator.kt#L33

With the knowlegde of this, you should be able to write a migration of the old and the know refresh token approach.

Did this help?
