### ISSUE TITLE
Mark some or all endpoints as Authenticated without annotation

### ISSUE THREAD

**Issue by obianachebe** [andretietz/retroauth#88]
I would like to authenticate some of my requests **without** using the `@Authenticated` annotation. I'm using a code generator to generate my client API and don't have access to change the headers. 

This is similar to the request here (#55) but it seems that the retroauth API has changed since.

My current solution is rewriting RetroauthCallAdapterFactory to not look for Authorized annotations like so:

```
override fun get(returnType: Type, annotations: Array<Annotation>, retrofit: Retrofit): CallAdapter<*, *>? {
        for (i in callAdapterFactories.indices) {
            val adapter = callAdapterFactories[i].get(returnType, annotations, retrofit)
            adapter?.let {
                return RetroauthCallAdapter(
                    adapter as CallAdapter<Any, Any>,
                    authenticator.getTokenType(),
                    authenticator.getOwnerType(),
                    methodCache
                )
            }
        }
        return null
    }
```

And then setting up my dagger Retrofit module to use Retroauth or a standard Retrofit Builder based on an `isAuthenticated` parameter

```
@Module
class RetrofitModule(private val isAuthenticated: Boolean = true) {
    @Provides
    @Singleton
    fun providesRetrofit(client: OkHttpClient, app: RootApp): Retrofit {
        val moshi = Moshi.Builder().add(ZonedDateTimeAdapter()).build()
        val moshiFactory = MoshiConverterFactory.create(moshi).withNullSerialization()

        val rxJavaAdapter = RxJava2CallAdapterFactory.create()

        return if (isAuthenticated) {
            val authenticator = AccountAuthenticator()

            val cache = AndroidMethodCache()
            val callAdapter = RetroauthCallAdapterFactory(
                listOf(rxJavaAdapter),
                authenticator,
                cache
            )

            val retroauthBuilder = Retroauth.Builder(
                authenticator,
                AndroidOwnerManager(app),
                AndroidTokenStorage(app),
                cache
            )

            return retroauthBuilder
                .baseUrl("https://my.host.com/")
                .addCallAdapterFactory(callAdapter)
                .addConverterFactory(moshiFactory)
                .client(client)
                .build()
        } else {
            Retrofit.Builder().baseUrl("https://my.host.com/")
                .addCallAdapterFactory(rxJavaAdapter)
                .addConverterFactory(moshiFactory)
                .client(client)
                .build()
        }
    }
}
```

This is working for now, but feels kinda clunky. What's the best way to get around using annotations?

**Comment by andretietz** [comment]
Hey, I am not sure If I fully understand your question. 

If you have calls that do not require authentication, then just don't add the annotation. You can even create a completely non-authenticated retrofit service with it.

What are you trying to achive? Give me a sample please.

**Comment by obianachebe** [comment]
@andretietz yes that's correct. I'm not thrilled about my current solution, but it's good enough. I don't know how common my use case is either.

I'm using Yelp's [codegen tool ]( https://github.com/Yelp/swagger-gradle-codegen) to convert my yaml API declarations to Retrofit interfaces which is why I can't annotate the headers myself. I'll probably move away from this down the road for more flexibility.
